# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               EyeCue Lab Notebook
description:         'EyeCue Lab is an agile software development firm. We build engaging solutions to complex problems.'
url:                 http://blog.eyecuelab.com
baseurl:             /
postimage:           /public/images/posts/
paginate:            5

# Custom vars
version:             1.0.0
